### ISSUE TITLE
require "css/datepicker" not found when starting app

### ISSUE THREAD

**Issue by icarito** [publiclab/mapmill#45]
The application won't start without commenting out the line in
app/assets/stylesheets/application.css.erb

This is in a new installation with having done all the bundle install / bower install steps.

**Comment by jywarren** [comment]
I believe #46 solves this; can you try pulling from master again?

**Comment by jywarren** [comment]
OK, sorry -- i **believe** this latest PR fixes it, and one other bug I anticipate we'll see.

**Comment by icarito** [comment]
Yup, that worked.

**Comment by jywarren** [comment]
Super!!!
