### ISSUE TITLE
OpenId login not working, possibly SSL related

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapmill#56]
I'm trying to log into https://mapmill.org with username "warren" -- i'm already logged into OpenID host at https://publiclab.org.

I get directed to this URL: 

https://publiclab.org/openid?openid.claimed_id=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.identity=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=https%3A%2F%2Fmapmill.org&openid.return_to=https%3A%2F%2Fmapmill.org%2Flogin%3Fauthenticity_token%3D9ESZjScGAMVinSBOQj18uDfW1NwHFjF5PPPPYlDk6Dk%253D%26back_to%3D%26open_id%3Dwarren&openid.sreg.required=nickname%2Cemail

Then, I click "Yes" to "Do you trust https://mapmill.org with your identity?", and get directed back to https://mapmill.org/ :

> User can not be associated to local account. Be sure to use the correct capitalization for your username!

The error seems related to the CA authority:

```
I, [2016-12-12T15:24:49.477377 #5502]  INFO -- : Started GET "/" for 72.215.51.8 at 2016-12-12 15:24:49 +0000
I, [2016-12-12T15:24:49.478711 #5502]  INFO -- : Processing by HomeController#front as HTML
I, [2016-12-12T15:24:49.491081 #5502]  INFO -- :   Rendered sites/_small_list.html.erb (10.2ms)
I, [2016-12-12T15:24:49.492356 #5502]  INFO -- :   Rendered sites/_form.html.erb (1.0ms)
I, [2016-12-12T15:24:49.492472 #5502]  INFO -- :   Rendered home/front.html.erb within layouts/application (12.6ms)
I, [2016-12-12T15:24:49.493520 #5502]  INFO -- : Completed 200 OK in 15ms (Views: 12.0ms | ActiveRecord: 1.8ms)
I, [2016-12-12T15:25:25.529249 #5502]  INFO -- : Started GET "/show_login" for 72.215.51.8 at 2016-12-12 15:25:25 +0000
I, [2016-12-12T15:25:25.530433 #5502]  INFO -- : Processing by SessionController#show_login as HTML
I, [2016-12-12T15:25:25.531858 #5502]  INFO -- :   Rendered session/_login_form.html.erb (0.3ms)
I, [2016-12-12T15:25:25.531957 #5502]  INFO -- :   Rendered session/show_login.html.erb within layouts/application (0.5ms)
I, [2016-12-12T15:25:25.532900 #5502]  INFO -- : Completed 200 OK in 2ms (Views: 1.7ms | ActiveRecord: 0.0ms)
I, [2016-12-12T15:25:35.222286 #5502]  INFO -- : Started GET "/login?authenticity_token=9ESZjScGAMVinSBOQj18uDfW1NwHFjF5PPPPYlDk6Dk%3D&back_to=&open_id=warren" for 72.215.51.8 at 2016-12-12 15:25:35 +0000
I, [2016-12-12T15:25:35.223529 #5502]  INFO -- : Processing by SessionController#login_openid as HTML
I, [2016-12-12T15:25:35.223589 #5502]  INFO -- :   Parameters: {"authenticity_token"=>"9ESZjScGAMVinSBOQj18uDfW1NwHFjF5PPPPYlDk6Dk=", "back_to"=>"", "open_id"=>"warren"}
I, [2016-12-12T15:25:35.224277 #5502]  INFO -- : Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)
I, [2016-12-12T15:25:35.224850 #5502]  INFO -- : WARNING: making https request to https://publiclab.org/people/warren/identity without verifying server certificate; no CA path was specified.
I, [2016-12-12T15:25:35.237447 #5502]  INFO -- : WARNING: making https request to https://publiclab.org/openid/warren without verifying server certificate; no CA path was specified.
I, [2016-12-12T15:25:35.253698 #5502]  INFO -- : Generated checkid_setup request to https://publiclab.org/openid using stateless mode.
I, [2016-12-12T15:26:23.417396 #5502]  INFO -- : Started GET "/login?authenticity_token=9ESZjScGAMVinSBOQj18uDfW1NwHFjF5PPPPYlDk6Dk%3D&back_to=&open_id=warren&openid.assoc_handle=%7BHMAC-SHA1%7D%7B584ec372%7D%7BOpyj0g%3D%3D%7D&openid.claimed_id=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.identity=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.op_endpoint=https%3A%2F%2Fpubliclab.org%2Fopenid&openid.response_nonce=2016-12-12T15%3A34%3A10Z7tdXwo&openid.return_to=https%3A%2F%2Fmapmill.org%2Flogin%3Fauthenticity_token%3D9ESZjScGAMVinSBOQj18uDfW1NwHFjF5PPPPYlDk6Dk%253D%26back_to%3D%26open_id%3Dwarren&openid.sig=4a3iQaAqlX5rIzkwMZCEjfsUJFQ%3D&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cns.sreg%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Csigned%2Csreg.email%2Csreg.nickname&openid.sreg.email=jeff%40publiclab.org&openid.sreg.nickname=warren" for 72.215.51.8 at 2016-12-12 15:26:23 +0000
I, [2016-12-12T15:26:23.422028 #5502]  INFO -- : Using 'check_authentication' with https://publiclab.org/openid
I, [2016-12-12T15:26:23.422992 #5502]  INFO -- : WARNING: making https request to https://publiclab.org/openid without verifying server certificate; no CA path was specified.
```

@icarito - any insight into this one? I think it still has to do with turning on SSL for MapMill and PublicLab.org -- specifically the line "WARNING: making https request to https://publiclab.org/openid/warren without verifying server certificate; no CA path was specified."

**Comment by jywarren** [comment]
OK it seems a quick solution for the `config/environment.rb` file is shown here: http://www.redmine.org/issues/15736

**Comment by jywarren** [comment]
Although it's not clear to me whether this goes on the server or the client?

**Comment by icarito** [comment]
Confirmed! I'll check it out.

**Comment by icarito** [comment]
Do you know for sure those warnings have to do with the error?

It doesn't immediately seem related to me.

**Comment by icarito** [comment]
I, [2016-12-12T15:25:35.222286 #5502]  INFO -- : Started GET
"/login?authenticity_token=9ESZjScGAMVinSBOQj18uDfW1NwHFjF5PPPPYlDk6Dk%3D&back_to=&open_id=warren"
for 72.215.51.8 at 2016-12-12 15:25:35
+0000                                                                           
I, [2016-12-12T15:25:35.223529 #5502]  INFO -- : Processing by
SessionController#login_openid as
HTML                                       I,
[2016-12-12T15:25:35.223589 #5502]  INFO -- :   Parameters:
{"authenticity_token"=>"9ESZjScGAMVinSBOQj18uDfW1NwHFjF5PPPPYlDk6Dk=",
"back_to"=>"",
"open_id"=>"warren"}                                                                                                              
*I, [2016-12-12T15:25:35.224277 #5502]  INFO -- : Completed 401
Unauthorized in 1ms (ActiveRecord:
0.0ms)*                                    I,
[2016-12-12T15:25:35.224850 #5502]  INFO -- : WARNING: making https
request to https://publiclab.org/people/warren/identity without
verifying server certificate; no CA path was
specified.                                                                                         
I, [2016-12-12T15:25:35.237447 #5502]  INFO -- : WARNING: making https
request to https://publiclab.org/openid/warren without verifying server
certificate; no CA path was
specified.                                                                                                  
I, [2016-12-12T15:25:35.253698 #5502]  INFO -- : Generated checkid_setup
request to https://publiclab.org/openid using stateless mode.  

The question is what is responding with 401 status. I'll test the openid
endpoint with another service.

**Comment by icarito** [comment]
Without other clues I'll look into that solution.

**Comment by icarito** [comment]
Actually, looking deeper, Mapknitter doesn't have this setting and it
works, so it must be something else.

**Comment by jywarren** [comment]
I think actually it might be a failure of `@user.save!` on this line:

https://github.com/publiclab/mapmill/blob/ee8e7f81998a5351ed505ab6cf58e12a92763e61/app/controllers/session_controller.rb#L48

This line is rescued, so we never see the real error. I can add a proper error output to it to find the real issue. Thanks, Sebastian, i'll take over for now!

**Comment by icarito** [comment]
Thanks Jeff, glad to be of service!

**Comment by jywarren** [comment]
Investigating in #57

**Comment by jywarren** [comment]
Actually it was that the saved `identity_url`s in the database were all pointed at `http` not `https` -- so this only affected existing users. Fixed now!

```ruby
User.all.each do |u|
  u.identity_url = u.identity_url.gsub('http:','https:')
  u.save
end
```

We could add that to a migration but i just did it in the console. Great!

**Comment by icarito** [comment]
Yay :-)
